/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Country;
import Model.Immigrant;
import Service.CountryService;
import Service.ImmigrantService;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Naome
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() throws NotBoundException {
        initComponents();
           //setExtendedState(JFrame.MAXIMIZED_BOTH); 
           this.setLocationRelativeTo(null);
           updateCountryCountLabel();
          updateImmigrantLabel();
    }
 private void disableBindPanel() {
    // Disable components in the BindPanel
    immigraDisplay.setEnabled(false);
    IssuedVisa1.setEnabled(false);
    //visaDisplay.setEnabled(false);
    CountryDisplay.setEnabled(false);
    //IssuedVisa4.setEnabled(false);
    IssuedVisa5.setEnabled(false);
 
    embassyLabel.setEnabled(false);
}
  private void enableBindPanel() {
        // Enable components in the BindPanel
        immigraDisplay.setEnabled(true);
        IssuedVisa1.setEnabled(true);
        //visaDisplay.setEnabled(true);
        CountryDisplay.setEnabled(true);
        //IssuedVisa4.setEnabled(true);
        IssuedVisa5.setEnabled(true);
       
        embassyLabel.setEnabled(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        dashLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        eventsPanel = new javax.swing.JLabel();
        visaPanel = new javax.swing.JPanel();
        VisaLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        immigrantPanel = new javax.swing.JLabel();
        CountryDirecting = new javax.swing.JPanel();
        countryLabel1 = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        embassyLabel = new javax.swing.JLabel();
        BindPanel = new javax.swing.JDesktopPane();
        jPanel9 = new javax.swing.JPanel();
        immigraDisplay = new javax.swing.JLabel();
        IssuedVisa1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        CountryDisplay = new javax.swing.JLabel();
        IssuedVisa5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(900, 670));
        setPreferredSize(new java.awt.Dimension(944, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("IMMIGRATION MANAGMENT SYSTEM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/male_user_50px.png"))); // NOI18N
        jLabel2.setText("HELLO admin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 150, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/search_26px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 90));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));

        dashLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        dashLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconee/icons8_dashboard_layout_24px.png"))); // NOI18N
        dashLabel.setText("DASHBOARD");
        dashLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(dashLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(dashLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 80));

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));

        eventsPanel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        eventsPanel.setForeground(new java.awt.Color(255, 255, 255));
        eventsPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconee/icons8_organization_32px.png"))); // NOI18N
        eventsPanel.setText("      EVENTS");
        eventsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventsPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(eventsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eventsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        visaPanel.setBackground(new java.awt.Color(0, 0, 204));

        VisaLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        VisaLabel.setForeground(new java.awt.Color(255, 255, 255));
        VisaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconee/icons8_travel_visa_50px.png"))); // NOI18N
        VisaLabel.setText("        VISA");
        VisaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisaLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout visaPanelLayout = new javax.swing.GroupLayout(visaPanel);
        visaPanel.setLayout(visaPanelLayout);
        visaPanelLayout.setHorizontalGroup(
            visaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, visaPanelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(VisaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        visaPanelLayout.setVerticalGroup(
            visaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VisaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.add(visaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 204));

        immigrantPanel.setBackground(new java.awt.Color(255, 255, 255));
        immigrantPanel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        immigrantPanel.setForeground(new java.awt.Color(255, 255, 255));
        immigrantPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconee/icons8_joining_queue_32px.png"))); // NOI18N
        immigrantPanel.setText("IMMIGRANTS");
        immigrantPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                immigrantPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(immigrantPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(immigrantPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 200, 80));

        CountryDirecting.setBackground(new java.awt.Color(0, 0, 204));
        CountryDirecting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CountryDirectingMouseClicked(evt);
            }
        });

        countryLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        countryLabel1.setForeground(new java.awt.Color(255, 255, 255));
        countryLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconee/icons8_europe_50px_1.png"))); // NOI18N
        countryLabel1.setText("COUNTRY");
        countryLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countryLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CountryDirectingLayout = new javax.swing.GroupLayout(CountryDirecting);
        CountryDirecting.setLayout(CountryDirectingLayout);
        CountryDirectingLayout.setHorizontalGroup(
            CountryDirectingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CountryDirectingLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(countryLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );
        CountryDirectingLayout.setVerticalGroup(
            CountryDirectingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CountryDirectingLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(countryLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(CountryDirecting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 80));

        logoutPanel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        logoutPanel.setForeground(new java.awt.Color(255, 255, 255));
        logoutPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconee/icons8_sign_out_32px.png"))); // NOI18N
        logoutPanel.setText("Logout");
        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
        });
        jPanel2.add(logoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 158, 51));

        jPanel6.setBackground(new java.awt.Color(0, 0, 204));

        embassyLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        embassyLabel.setForeground(new java.awt.Color(255, 255, 255));
        embassyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconee/icons8_red_fort_32px.png"))); // NOI18N
        embassyLabel.setText("EMBASSY");
        embassyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                embassyLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(embassyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(embassyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 180, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 580));

        BindPanel.setBackground(new java.awt.Color(255, 255, 255));
        BindPanel.setPreferredSize(new java.awt.Dimension(700, 580));

        jPanel9.setBackground(new java.awt.Color(0, 51, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 255, 255)));

        immigraDisplay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        immigraDisplay.setText("1000");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(immigraDisplay)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(immigraDisplay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        IssuedVisa1.setText("COUNTRY PARTNER");

        jPanel11.setBackground(new java.awt.Color(0, 51, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 255, 255)));

        CountryDisplay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(CountryDisplay)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(CountryDisplay)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        IssuedVisa5.setText("ALL IMMIGRANTS");

        BindPanel.setLayer(jPanel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BindPanel.setLayer(IssuedVisa1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BindPanel.setLayer(jPanel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BindPanel.setLayer(IssuedVisa5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout BindPanelLayout = new javax.swing.GroupLayout(BindPanel);
        BindPanel.setLayout(BindPanelLayout);
        BindPanelLayout.setHorizontalGroup(
            BindPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BindPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BindPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BindPanelLayout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BindPanelLayout.createSequentialGroup()
                        .addComponent(IssuedVisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(IssuedVisa5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(344, Short.MAX_VALUE))
        );
        BindPanelLayout.setVerticalGroup(
            BindPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BindPanelLayout.createSequentialGroup()
                .addGroup(BindPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BindPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(IssuedVisa1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BindPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(IssuedVisa5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(396, Short.MAX_VALUE))
        );

        getContentPane().add(BindPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 710, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void countryLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countryLabel1MouseClicked
                                                
      disableBindPanel();
    Countriiii countryFrame = new Countriiii();
    BindPanel.removeAll();
    BindPanel.add(countryFrame);
    countryFrame.setSize(BindPanel.getSize());
    countryFrame.setVisible(true);
    //countryFrame.setSelected(true);
                                                

    }//GEN-LAST:event_countryLabel1MouseClicked

    private void CountryDirectingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CountryDirectingMouseClicked
//      disableBindPanel();
//    Countriiii countryFrame = new Countriiii();
//    BindPanel.removeAll();
//    BindPanel.add(countryFrame);
//    countryFrame.setSize(BindPanel.getSize());
//    countryFrame.setVisible(true);
//    //countryFrame.setSelected(true);
    }//GEN-LAST:event_CountryDirectingMouseClicked

    private void VisaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisaLabelMouseClicked
        disableBindPanel();
        VisaForm visaF=new VisaForm();
    BindPanel.removeAll();
    BindPanel.add(visaF);
    visaF.setSize(BindPanel.getSize());
    visaF.setVisible(true); 
    }//GEN-LAST:event_VisaLabelMouseClicked

    private void embassyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_embassyLabelMouseClicked
        disableBindPanel();
        EmbassyForm embaF=new EmbassyForm();
    BindPanel.removeAll();
    BindPanel.add(embaF);
   embaF.setSize(BindPanel.getSize());
   embaF.setVisible(true); 
    }//GEN-LAST:event_embassyLabelMouseClicked

    private void eventsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventsPanelMouseClicked
        // TODO add your handling code here:
      disableBindPanel();
     IntentForm embaF =new IntentForm();
    BindPanel.removeAll();
    BindPanel.add(embaF);
   embaF.setSize(BindPanel.getSize());
   embaF.setVisible(true);
    }//GEN-LAST:event_eventsPanelMouseClicked

    private void immigrantPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_immigrantPanelMouseClicked
        disableBindPanel();
     ImmigracaoF form=new ImmigracaoF();
    BindPanel.removeAll();
    BindPanel.add(form);
   form.setSize(BindPanel.getSize());
   form.setVisible(true);
    }//GEN-LAST:event_immigrantPanelMouseClicked

    private void dashLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashLabelMouseClicked
     
        // Add components or perform actions specific to the Dashboard view
          BindPanel.removeAll();
    
   
    
    enableBindPanel();
    }//GEN-LAST:event_dashLabelMouseClicked

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked
        // got login page
         this.dispose();

    // Open the login window
    Login loginFrame = new Login();
    loginFrame.setVisible(true);
    }//GEN-LAST:event_logoutPanelMouseClicked
private void updateCountryCountLabel() throws NotBoundException {
        try {
             Registry reg=LocateRegistry.getRegistry("127.0.0.1", 5000);
            CountryService paises =(CountryService) reg.lookup("pais");
             Country cnt=new Country();
            // Call the remote method to get the count
            int countryCount = paises.getnbrCountries();

           
         CountryDisplay.setText(countryCount + " countries");
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }
private void updateImmigrantLabel() throws NotBoundException {
        try {
             Registry reg=LocateRegistry.getRegistry("127.0.0.1", 5000);
            ImmigrantService immig=(ImmigrantService) reg.lookup("immigra");
            Immigrant dm =new Immigrant();
          
            // Call the remote method to get the count
            int countryCount = immig.getnbrImmigrants();

            // Update the label text with the count
         immigraDisplay.setText(countryCount + " immigrants");
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Dashboard().setVisible(true);
                } catch (NotBoundException ex) {
                    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane BindPanel;
    private javax.swing.JPanel CountryDirecting;
    private javax.swing.JLabel CountryDisplay;
    private javax.swing.JLabel IssuedVisa1;
    private javax.swing.JLabel IssuedVisa5;
    private javax.swing.JLabel VisaLabel;
    private javax.swing.JLabel countryLabel1;
    private javax.swing.JLabel dashLabel;
    private javax.swing.JLabel embassyLabel;
    private javax.swing.JLabel eventsPanel;
    private javax.swing.JLabel immigraDisplay;
    private javax.swing.JLabel immigrantPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel logoutPanel;
    private javax.swing.JPanel visaPanel;
    // End of variables declaration//GEN-END:variables
}
